import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MusicPlayerContextProvider } from '@/context/MusicPlayerContext'
import { Footer } from '@/components/Footer'
import { Aside } from '@/components/Aside'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Spotify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.variable} font-sans bg-zinc-900 text-zinc-50`}
      >
        <MusicPlayerContextProvider>
          <div className="h-screen flex flex-col">
            <div className="flex flex-1">
              <Aside />
              <div className='flex-1  overflow-auto h-[85vh]'>
                {children}

              </div>

            </div>
            <Footer />

          </div>


        </MusicPlayerContextProvider>
      </body>
    </html>
  )
}
